variable "aws_region" {}
variable "vpc_name" {}
variable vpc_cidr_block {}
variable private_subnet_cidr_blocks {}
variable public_subnet_cidr_blocks {}
variable "ami_id" {}
variable "nat_ami" {}
variable "instance_type" {}
variable "db_instance_class" {}
variable "instance_names" {}
variable "alb_igw_frontend_name" {}
variable "alb_frontend_backend_name" {}
variable "aws_key_pair" {}
variable "db_subnet_group_name" {}
variable "db_user" {}
variable "db_pwd" {}