---
- name: Configure bastion/host
  hosts: bastion_hosts
  gather_facts: true
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Ansible
      ansible.builtin.package:
        name: ansible
        state: present  
        
    - name: Add desired block of text to /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1     localhost
          54.85.121.209 bastion-host
          10.0.2.80    frontend
          10.0.3.155    backend
          44.203.50.22  nat-instance
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Add desired block of text to /etc/ansible/hosts
      ansible.builtin.blockinfile:
        path: /etc/ansible/hosts
        block: |
          [managed_nodes]
          bastion-host ansible_host=54.85.121.209
          frontend ansible_host=10.0.2.80
          backend ansible_host=10.0.3.155
          nat-instance ansible_host=44.203.50.22 ansible_user=ec2-user
        marker: "# {mark} ANSIBLE MANAGED BLOCK"


