---
- name: Configure Docker on Backend
  hosts: backend
  become: true
  vars:
    pkg_mgr: "apt"
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker image for App API
      docker_image:
        name: "josephsjr/movie-analyst-api:5.00"
        source: pull
      become: true

    - name: Run Docker App API Container
      docker_container:
        name: backend-container
        image: "josephsjr/movie-analyst-api:5.00"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"  
