---
- name: Configure Docker on Frontend
  hosts: frontend
  become: true
  vars:
    pkg_mgr: "apt"
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker image for App UI
      docker_image:
        name: "josephsjr/movie-analyst-ui:2.00"
        source: pull
      become: true

    - name: Run Docker App UI Container
      docker_container:
        name: frontend-container
        image: "josephsjr/movie-analyst-ui:2.00"
        state: started
        restart_policy: always
        ports:
          - "80:80"  

